// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SalesTaxCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("amount")]
        public long Amount { get; set; }

        [JsonProperty("taxRate")]
        public double TaxRate { get; set; }

        [JsonProperty("taxRatePercent")]
        public double TaxRatePercent { get; set; }

        [JsonProperty("taxAmount")]
        public double TaxAmount { get; set; }

        [JsonProperty("totalAmount")]
        public double TotalAmount { get; set; }

        [JsonProperty("zip")]
        public long Zip { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("breakdown")]
        public Breakdown Breakdown { get; set; }
    }

    public partial class Breakdown
    {
        [JsonProperty("stateRate")]
        public double StateRate { get; set; }

        [JsonProperty("countyRate")]
        public double CountyRate { get; set; }

        [JsonProperty("cityRate")]
        public double CityRate { get; set; }

        [JsonProperty("specialRate")]
        public double SpecialRate { get; set; }
    }
}
